name = "url-shortener"
type = "javascript"
workers_dev = true
compatibility_date = "2024-03-01"

kv_namespaces = [
  { binding = "KV", id = "f9656cde0b994972ab074a9a3c962979"},
]

[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-  wrangler/configuration
