name = "cloudflare-url-shortener"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "KV", id = "a9b76f023a6f4f5b8ab94920fa0edd84", preview_id = "2d870490f0864168b65ae9fac9e483f2" },
]

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
